### PR TITLE
Added a FileName binding Tooltip to the TextBlock of the tab.

### LINKED ISSUE #280: Add a tooltip on the editor tabs with the full path to the file, similar to Visual Studio.
**Is your feature request related to a problem? Please describe.**
I very often have many DAX files of the same name, and I need to differentiate which is which, exactly.  I can't do that now.

**Describe the solution you'd like**
A tooltip on the UI tab of the editor.

### PR DESCRIPTION
**Pull request by dmarkle**
Fixes #280

### CODE REVIEW

**Comment by dgosbell** [comment]
Thanks for this, I've merged this in and it will go out as part of the next release.

**Comment by dmarkle** [comment]
@dgosbell I'm trying to run DaxStudio.Standalone on my box so I can debug, and when I run it I get **Could not load file or assembly 'FontAwesome.WPF, PublicKeyToken=0758b07a11a4f466' or one of its dependencies. The system cannot find the file specified.**' 

What am I missing?  Sorry if I missed/ignored a readme you wrote...

**Comment by dgosbell** [comment]
hmm, I can't see any issues with that package on my system. All our external dependencies come from nuget packages so in theory using VS2019 and doing a ```git clone``` and ```nuget restore``` should be all that's required to get a dev environment up and running (and Visual Studio should do the nuget restore automatically unless you have that switched off). All our releases are done using an AppVeyor build server which helps ensure that we don't accidentally include any local dependencies. 

However I did see someone else on twitter mention that they had to upgrade this package before the solution would build, but I'm not entirely sure what they were talking about because as far as I can see we're already using the latest version.

Can you see the FontAwesome.wpf.dll file in the /src/bin/debug folder after you do a debug build? If you can't you'll need to check if that nuget package has downloaded and if the reference is still set to copy local. If the file is there it could maybe be an issue with one of its dependencies and you could look at turning on fusion logging (see the startup logging section here [https://daxstudio.org/documentation/troubleshooting/logging-settings/](https://daxstudio.org/documentation/troubleshooting/logging-settings/) or use the menu option in DaxStudio.Checker to switch this on)  as this will let you see what the .net framework is having trouble loading.

**Comment by dgosbell** [comment]
Ok, so when I cloned to a fresh VM I get the same error, but when I switched to the develop branch the error went away (which makes no sense as the develop branch is currently only a few commits ahead of master and nothing has changed in regards to this dependency). 

I also noticed that the configuration was showing as Mixed instead of AnyCPU and changing this also seems to fix the issue (which does not make any sense to me either). It's very strange, I don't have a good explanation for why this particular dependency is playing up. (manually copying the dll to your /bin/debug output folder should also "fix" this issue).

I'll try to do a few more comparisons between the working and broken versions to see if I can figure out why this is behaving strange.

**Comment by dmarkle** [comment]
Ah, yes.  I can confirm switching to AnyCPU does the trick.  Thanks.  Looks
like the Configurations in the solution is a bit messed up generally -- the
Mixed thing in particular.  Maybe the only config we should even have is
just AnyCPU?

**Pull request merged**
